# Docker Compose override file for testing/CI environments
# Usage: docker-compose -f docker-compose.yml -f docker-compose.test.yml up
# This file uses MongoDB Atlas for testing with MOCK_MONGODB_URI

services:
  # Override backend-service for testing
  backend-service:
    environment:
      - ENV=dev
      - RUNNING_TESTS=true
      # Use MongoDB Atlas for testing with MOCK_MONGODB_URI
      - MONGODB_URI=${MOCK_MONGODB_URI}
      - MONGODB_DATABASE=${MOCK_MONGODB_DATABASE:-test_database}
      - MONGODB_CONTEXT_COLLECTION=${MONGODB_CONTEXT_COLLECTION:-contexts}
      - MONGODB_AGENT_COLLECTION=${MONGODB_AGENT_COLLECTION:-agents}
      - MONGODB_DOCUMENTS_COLLECTION=${MONGODB_DOCUMENTS_COLLECTION:-documents}
      - RAG_DATABASE_SYSTEM=mongodb
      # Test LLM keys (should be set in CI or .env)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-test_key}
      - GPT_MODEL=${GPT_MODEL:-gpt-4o-mini}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-test_key}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash-lite}
      - ACCESS_SERVICE=mock
    ports:
      - "8000:8000"  # Expose for testing

  # Disable nginx in test mode
  nginx:
    profiles:
      - disabled
