# Docker Compose Configuration for RAGdoll Application with Local MongoDB
# Purpose: Development environment with containerized MongoDB
# Usage: docker compose -f docker-compose.local.yml up --build

# Project name for Docker Desktop - keeps containers under one project
name: ragdoll

services:
  # FastAPI Backend Service
  chat-service:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ragdoll-backend:latest  # Named image - prevents duplicate images
    container_name: ragdoll-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for hot-reload during development
      - .:/app
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Override MongoDB URI to use local container
      MONGODB_URI: mongodb://mongodb:27017

  # MongoDB Database Service
  mongodb:
    image: mongo:latest
    container_name: ragdoll-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo-data: {}
