@startuml PhysicalView
node "VR Environment" {
  component "Action Manager\n(Chat Service Module)" as AM
}
node "Docker Host" {
node "Chat Service Microservice Infrastructure" {
  node "RAG " {
    component "RAG Entry" as RAG_Entry

    component "LLM Facade" as LLM
  }
  database "MongoDB Atlas" as DB
  database "Local Mock Database" as MockDB
}
}

AM --> RAG_Entry : HTTPS Request
RAG_Entry --> DB : Data access via DAO
RAG_Entry --> MockDB : Data access via DAO
RAG_Entry --> LLM : API call to LLM service
@enduml
