@startuml
title Git Flow Development Workflow (Manual Testing)


skinparam monochrome true
skinparam defaultTextAlignment left

rectangle "Repository" {
    rectangle "Main (production)" as Main
    rectangle "Develop" as Develop
}
actor Developer




[Feature Branch] as Feature
[Hotfix Branch] as Hotfix

Developer --> Feature : Create feature branch\nfrom 'Develop'
Feature --> Develop : Merge after\nfeature complete


Hotfix --> Main : Merge after testing
Developer --> Hotfix : Create hotfix branch\nfrom 'Main'
Hotfix --> Develop : Merge back changes


@enduml
