from enum import Enum, auto

class GraphDatabaseType(Enum):
    """
    Enum for chunk database types.
    """
    NEO4J = auto()

class NodeType(Enum):
    PERSON = auto()
    PHILOSOPHER = auto()
    SCIENTIST = auto()
    IDEA = auto()
    CONCEPT = auto()
    FORMULA = auto()
    THEOREM = auto()
    IDENTITY = auto()
    METHOD = auto()
    PRINCIPLE = auto()
    EQUATION = auto()
    BOOK = auto()
    PUBLICATION = auto()
    PAPER = auto()
    TREATISE = auto()
    LOCATION = auto()
    CITY = auto()
    COUNTRY = auto()
    INSTITUTION = auto()
    UNIVERSITY = auto()
    SOCIETY = auto()
    AREA = auto()
    DISCIPLINE = auto()
    TOPIC = auto()
    EVENT = auto()
    DISCOVERY = auto()
    APPLICATION = auto()

class EdgeType(Enum):
    AUTHORED = auto()
    INTRODUCED = auto()
    FORMULATED = auto()
    PROPOSED = auto()
    PUPIL_OF = auto()
    MENTOR_OF = auto()
    INFLUENCED = auto()
    DERIVED_FROM = auto()
    BELONGS_TO = auto()
    STUDIED_IN = auto()
    PART_OF = auto()
    LIVED_IN = auto()
    BORN_IN = auto()
    WORKED_AT = auto()
    CHILD_OF = auto()
    SIBLING_OF = auto()
    SPOUSE_OF = auto()
    DESCRIBES = auto()
    REFERENCES = auto()
    RELATED_TO = auto()
    KNOWS = auto()